// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.26.1
// source: proto/common/matchgame.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 牌
type Tag struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TagId      int32  `protobuf:"varint,1,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`    // 标签id
	X          int32  `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`                         //x坐标
	Y          int32  `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`                         //y坐标
	Multiple   int32  `protobuf:"varint,4,opt,name=multiple,proto3" json:"multiple,omitempty"`           // 标签的倍数
	IsWild     bool   `protobuf:"varint,5,opt,name=is_wild,json=isWild,proto3" json:"is_wild,omitempty"` // 是否百搭
	Redundancy string `protobuf:"bytes,6,opt,name=redundancy,proto3" json:"redundancy,omitempty"`        //冗余 slotId-value
	// 7-int  可选[0,1,2,3,4,5]  slot7-技能编号 0-没技能
	// 16-int 可选[0,1,2,4,8......128]   slot16-隐藏翻倍 0-没翻倍 1-没翻倍,特殊显示,>=2 翻倍
	IsMegastack bool `protobuf:"varint,7,opt,name=is_megastack,json=isMegastack,proto3" json:"is_megastack,omitempty"` //是否是变换标签变来的
}

func (x *Tag) Reset() {
	*x = Tag{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_common_matchgame_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_matchgame_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_proto_common_matchgame_proto_rawDescGZIP(), []int{0}
}

func (x *Tag) GetTagId() int32 {
	if x != nil {
		return x.TagId
	}
	return 0
}

func (x *Tag) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Tag) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Tag) GetMultiple() int32 {
	if x != nil {
		return x.Multiple
	}
	return 0
}

func (x *Tag) GetIsWild() bool {
	if x != nil {
		return x.IsWild
	}
	return false
}

func (x *Tag) GetRedundancy() string {
	if x != nil {
		return x.Redundancy
	}
	return ""
}

func (x *Tag) GetIsMegastack() bool {
	if x != nil {
		return x.IsMegastack
	}
	return false
}

// 牌列表
type Tags struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tags        []*Tag `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`      //牌id列表
	Amount      int64  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"` //倍数
	Point       int32  `protobuf:"varint,3,opt,name=point,proto3" json:"point,omitempty"`
	Orientation int32  `protobuf:"varint,4,opt,name=Orientation,proto3" json:"Orientation,omitempty"` //0 左 1 右
}

func (x *Tags) Reset() {
	*x = Tags{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_common_matchgame_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tags) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tags) ProtoMessage() {}

func (x *Tags) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_matchgame_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tags.ProtoReflect.Descriptor instead.
func (*Tags) Descriptor() ([]byte, []int) {
	return file_proto_common_matchgame_proto_rawDescGZIP(), []int{1}
}

func (x *Tags) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Tags) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Tags) GetPoint() int32 {
	if x != nil {
		return x.Point
	}
	return 0
}

func (x *Tags) GetOrientation() int32 {
	if x != nil {
		return x.Orientation
	}
	return 0
}

// 步骤流程
type StepFlow struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index       int64       `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`                                    //索引
	Gain        int64       `protobuf:"varint,2,opt,name=gain,proto3" json:"gain,omitempty"`                                      //总赢取
	RemoveList  []*Tags     `protobuf:"bytes,3,rep,name=remove_list,json=removeList,proto3" json:"remove_list,omitempty"`         //移除的牌列表
	AddList     *Tags       `protobuf:"bytes,4,opt,name=add_list,json=addList,proto3" json:"add_list,omitempty"`                  //新增的牌
	Points      int32       `protobuf:"varint,5,opt,name=points,proto3" json:"points,omitempty"`                                  //积分点数 {6}
	RemoveCause int32       `protobuf:"varint,6,opt,name=remove_cause,json=removeCause,proto3" json:"remove_cause,omitempty"`     //消除的原因,remove_list为空的时候才生效 0:默认 1:积分技能 2: {6}
	SkillCenter []*Pos      `protobuf:"bytes,7,rep,name=skill_center,json=skillCenter,proto3" json:"skill_center,omitempty"`      //技能点 {6 }
	SpecialMul  []int32     `protobuf:"varint,8,rep,packed,name=special_mul,json=specialMul,proto3" json:"special_mul,omitempty"` //机台特殊翻倍
	AlterList   []*Tags     `protobuf:"bytes,9,rep,name=alter_list,json=alterList,proto3" json:"alter_list,omitempty"`            //替换的牌
	Accumulate  *Accumulate `protobuf:"bytes,10,opt,name=accumulate,proto3" json:"accumulate,omitempty"`                          //累积（积分/翻倍） {9}
}

func (x *StepFlow) Reset() {
	*x = StepFlow{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_common_matchgame_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StepFlow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepFlow) ProtoMessage() {}

func (x *StepFlow) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_matchgame_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepFlow.ProtoReflect.Descriptor instead.
func (*StepFlow) Descriptor() ([]byte, []int) {
	return file_proto_common_matchgame_proto_rawDescGZIP(), []int{2}
}

func (x *StepFlow) GetIndex() int64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *StepFlow) GetGain() int64 {
	if x != nil {
		return x.Gain
	}
	return 0
}

func (x *StepFlow) GetRemoveList() []*Tags {
	if x != nil {
		return x.RemoveList
	}
	return nil
}

func (x *StepFlow) GetAddList() *Tags {
	if x != nil {
		return x.AddList
	}
	return nil
}

func (x *StepFlow) GetPoints() int32 {
	if x != nil {
		return x.Points
	}
	return 0
}

func (x *StepFlow) GetRemoveCause() int32 {
	if x != nil {
		return x.RemoveCause
	}
	return 0
}

func (x *StepFlow) GetSkillCenter() []*Pos {
	if x != nil {
		return x.SkillCenter
	}
	return nil
}

func (x *StepFlow) GetSpecialMul() []int32 {
	if x != nil {
		return x.SpecialMul
	}
	return nil
}

func (x *StepFlow) GetAlterList() []*Tags {
	if x != nil {
		return x.AlterList
	}
	return nil
}

func (x *StepFlow) GetAccumulate() *Accumulate {
	if x != nil {
		return x.Accumulate
	}
	return nil
}

// 游戏步骤
type MatchSpinStep struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type       int32        `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`                        //// 游戏类型 1 normal_spin 2 free_spin 3: re_spin 4: re_spin_link
	Id         int32        `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`                            //id
	Pid        int32        `protobuf:"varint,3,opt,name=pid,proto3" json:"pid,omitempty"`                          //pid
	SumGain    int64        `protobuf:"varint,4,opt,name=sum_gain,json=sumGain,proto3" json:"sum_gain,omitempty"`   //总赢取
	InitList   []*Tags      `protobuf:"bytes,5,rep,name=init_list,json=initList,proto3" json:"init_list,omitempty"` //初始排布
	Flows      []*StepFlow  `protobuf:"bytes,6,rep,name=flows,proto3" json:"flows,omitempty"`                       //游戏流程
	SingleTags []*SingleTag `protobuf:"bytes,7,rep,name=single_tags,json=singleTags,proto3" json:"single_tags,omitempty"`
	TemInit    []int32      `protobuf:"varint,8,rep,packed,name=tem_init,json=temInit,proto3" json:"tem_init,omitempty"` //模版
	OtherLine  []*Tags      `protobuf:"bytes,9,rep,name=other_line,json=otherLine,proto3" json:"other_line,omitempty"`   //其他赢钱划线
}

func (x *MatchSpinStep) Reset() {
	*x = MatchSpinStep{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_common_matchgame_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchSpinStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchSpinStep) ProtoMessage() {}

func (x *MatchSpinStep) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_matchgame_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchSpinStep.ProtoReflect.Descriptor instead.
func (*MatchSpinStep) Descriptor() ([]byte, []int) {
	return file_proto_common_matchgame_proto_rawDescGZIP(), []int{3}
}

func (x *MatchSpinStep) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *MatchSpinStep) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MatchSpinStep) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *MatchSpinStep) GetSumGain() int64 {
	if x != nil {
		return x.SumGain
	}
	return 0
}

func (x *MatchSpinStep) GetInitList() []*Tags {
	if x != nil {
		return x.InitList
	}
	return nil
}

func (x *MatchSpinStep) GetFlows() []*StepFlow {
	if x != nil {
		return x.Flows
	}
	return nil
}

func (x *MatchSpinStep) GetSingleTags() []*SingleTag {
	if x != nil {
		return x.SingleTags
	}
	return nil
}

func (x *MatchSpinStep) GetTemInit() []int32 {
	if x != nil {
		return x.TemInit
	}
	return nil
}

func (x *MatchSpinStep) GetOtherLine() []*Tags {
	if x != nil {
		return x.OtherLine
	}
	return nil
}

// 下注回复
type MatchSpinAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Head         *AckHead         `protobuf:"bytes,1,opt,name=head,proto3" json:"head,omitempty"`                                      //头
	Opt          *SpinOpt         `protobuf:"bytes,2,opt,name=opt,proto3" json:"opt,omitempty"`                                        //下注配置
	TotalWin     int64            `protobuf:"varint,3,opt,name=total_win,json=totalWin,proto3" json:"total_win,omitempty"`             //总赢取
	TotalBet     int64            `protobuf:"varint,4,opt,name=total_bet,json=totalBet,proto3" json:"total_bet,omitempty"`             //总下注
	TotalRaise   int64            `protobuf:"varint,5,opt,name=total_raise,json=totalRaise,proto3" json:"total_raise,omitempty"`       //总加注
	Steps        []*MatchSpinStep `protobuf:"bytes,6,rep,name=steps,proto3" json:"steps,omitempty"`                                    //下注回复
	TxnId        int32            `protobuf:"varint,7,opt,name=txn_id,json=txnId,proto3" json:"txn_id,omitempty"`                      //交易id
	BeforeAmount int64            `protobuf:"varint,8,opt,name=before_amount,json=beforeAmount,proto3" json:"before_amount,omitempty"` //before余额
	AfterAmount  int64            `protobuf:"varint,9,opt,name=after_amount,json=afterAmount,proto3" json:"after_amount,omitempty"`    //after余额
}

func (x *MatchSpinAck) Reset() {
	*x = MatchSpinAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_common_matchgame_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchSpinAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchSpinAck) ProtoMessage() {}

func (x *MatchSpinAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_matchgame_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchSpinAck.ProtoReflect.Descriptor instead.
func (*MatchSpinAck) Descriptor() ([]byte, []int) {
	return file_proto_common_matchgame_proto_rawDescGZIP(), []int{4}
}

func (x *MatchSpinAck) GetHead() *AckHead {
	if x != nil {
		return x.Head
	}
	return nil
}

func (x *MatchSpinAck) GetOpt() *SpinOpt {
	if x != nil {
		return x.Opt
	}
	return nil
}

func (x *MatchSpinAck) GetTotalWin() int64 {
	if x != nil {
		return x.TotalWin
	}
	return 0
}

func (x *MatchSpinAck) GetTotalBet() int64 {
	if x != nil {
		return x.TotalBet
	}
	return 0
}

func (x *MatchSpinAck) GetTotalRaise() int64 {
	if x != nil {
		return x.TotalRaise
	}
	return 0
}

func (x *MatchSpinAck) GetSteps() []*MatchSpinStep {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *MatchSpinAck) GetTxnId() int32 {
	if x != nil {
		return x.TxnId
	}
	return 0
}

func (x *MatchSpinAck) GetBeforeAmount() int64 {
	if x != nil {
		return x.BeforeAmount
	}
	return 0
}

func (x *MatchSpinAck) GetAfterAmount() int64 {
	if x != nil {
		return x.AfterAmount
	}
	return 0
}

type Pos struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X int32 `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y int32 `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *Pos) Reset() {
	*x = Pos{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_common_matchgame_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pos) ProtoMessage() {}

func (x *Pos) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_matchgame_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pos.ProtoReflect.Descriptor instead.
func (*Pos) Descriptor() ([]byte, []int) {
	return file_proto_common_matchgame_proto_rawDescGZIP(), []int{5}
}

func (x *Pos) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Pos) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type SingleTag struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Single    *Tag   `protobuf:"bytes,1,opt,name=single,proto3" json:"single,omitempty"`
	FlowIndex int32  `protobuf:"varint,2,opt,name=flow_index,json=flowIndex,proto3" json:"flow_index,omitempty"` //初始生成的索引
	PosOder   []*Pos `protobuf:"bytes,3,rep,name=pos_oder,json=posOder,proto3" json:"pos_oder,omitempty"`        //位置变化的一个序列
	SubId     int32  `protobuf:"varint,4,opt,name=sub_id,json=subId,proto3" json:"sub_id,omitempty"`             //1,2,3
}

func (x *SingleTag) Reset() {
	*x = SingleTag{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_common_matchgame_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SingleTag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleTag) ProtoMessage() {}

func (x *SingleTag) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_matchgame_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleTag.ProtoReflect.Descriptor instead.
func (*SingleTag) Descriptor() ([]byte, []int) {
	return file_proto_common_matchgame_proto_rawDescGZIP(), []int{6}
}

func (x *SingleTag) GetSingle() *Tag {
	if x != nil {
		return x.Single
	}
	return nil
}

func (x *SingleTag) GetFlowIndex() int32 {
	if x != nil {
		return x.FlowIndex
	}
	return 0
}

func (x *SingleTag) GetPosOder() []*Pos {
	if x != nil {
		return x.PosOder
	}
	return nil
}

func (x *SingleTag) GetSubId() int32 {
	if x != nil {
		return x.SubId
	}
	return 0
}

type Accumulate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	General int32 `protobuf:"varint,1,opt,name=general,proto3" json:"general,omitempty"` //常规
	Left    int32 `protobuf:"varint,2,opt,name=left,proto3" json:"left,omitempty"`       //左边
	Right   int32 `protobuf:"varint,3,opt,name=right,proto3" json:"right,omitempty"`     //右边
	Points  int32 `protobuf:"varint,4,opt,name=points,proto3" json:"points,omitempty"`   //积分点数 （兼容）
}

func (x *Accumulate) Reset() {
	*x = Accumulate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_common_matchgame_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Accumulate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Accumulate) ProtoMessage() {}

func (x *Accumulate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_matchgame_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Accumulate.ProtoReflect.Descriptor instead.
func (*Accumulate) Descriptor() ([]byte, []int) {
	return file_proto_common_matchgame_proto_rawDescGZIP(), []int{7}
}

func (x *Accumulate) GetGeneral() int32 {
	if x != nil {
		return x.General
	}
	return 0
}

func (x *Accumulate) GetLeft() int32 {
	if x != nil {
		return x.Left
	}
	return 0
}

func (x *Accumulate) GetRight() int32 {
	if x != nil {
		return x.Right
	}
	return 0
}

func (x *Accumulate) GetPoints() int32 {
	if x != nil {
		return x.Points
	}
	return 0
}

var File_proto_common_matchgame_proto protoreflect.FileDescriptor

var file_proto_common_matchgame_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x6d,
	0x61, 0x74, 0x63, 0x68, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x1a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xb0, 0x01, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x12, 0x15, 0x0a, 0x06, 0x74, 0x61, 0x67,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x74, 0x61, 0x67, 0x49, 0x64,
	0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x78, 0x12, 0x0c,
	0x0a, 0x01, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x79, 0x12, 0x1a, 0x0a, 0x08,
	0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08,
	0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x73, 0x5f, 0x77,
	0x69, 0x6c, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x69, 0x73, 0x57, 0x69, 0x6c,
	0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x64, 0x75, 0x6e, 0x64, 0x61, 0x6e, 0x63, 0x79, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x64, 0x75, 0x6e, 0x64, 0x61, 0x6e, 0x63,
	0x79, 0x12, 0x21, 0x0a, 0x0c, 0x69, 0x73, 0x5f, 0x6d, 0x65, 0x67, 0x61, 0x73, 0x74, 0x61, 0x63,
	0x6b, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x69, 0x73, 0x4d, 0x65, 0x67, 0x61, 0x73,
	0x74, 0x61, 0x63, 0x6b, 0x22, 0x77, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x12, 0x1f, 0x0a, 0x04,
	0x74, 0x61, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x74, 0x61, 0x67, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x12, 0x16, 0x0a,
	0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x61,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x4f,
	0x72, 0x69, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0b, 0x4f, 0x72, 0x69, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xfa, 0x02,
	0x0a, 0x09, 0x73, 0x74, 0x65, 0x70, 0x5f, 0x66, 0x6c, 0x6f, 0x77, 0x12, 0x14, 0x0a, 0x05, 0x69,
	0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65,
	0x78, 0x12, 0x12, 0x0a, 0x04, 0x67, 0x61, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x04, 0x67, 0x61, 0x69, 0x6e, 0x12, 0x2d, 0x0a, 0x0b, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x5f,
	0x6c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x74, 0x61, 0x67, 0x73, 0x52, 0x0a, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x08, 0x61, 0x64, 0x64, 0x5f, 0x6c, 0x69, 0x73, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x74, 0x61, 0x67, 0x73, 0x52, 0x07, 0x61, 0x64, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x70,
	0x6f, 0x69, 0x6e, 0x74, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x5f,
	0x63, 0x61, 0x75, 0x73, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x72, 0x65, 0x6d,
	0x6f, 0x76, 0x65, 0x43, 0x61, 0x75, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x0c, 0x73, 0x6b, 0x69, 0x6c,
	0x6c, 0x5f, 0x63, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b,
	0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x6f, 0x73, 0x52, 0x0b, 0x73, 0x6b, 0x69,
	0x6c, 0x6c, 0x43, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x70, 0x65, 0x63,
	0x69, 0x61, 0x6c, 0x5f, 0x6d, 0x75, 0x6c, 0x18, 0x08, 0x20, 0x03, 0x28, 0x05, 0x52, 0x0a, 0x73,
	0x70, 0x65, 0x63, 0x69, 0x61, 0x6c, 0x4d, 0x75, 0x6c, 0x12, 0x2b, 0x0a, 0x0a, 0x61, 0x6c, 0x74,
	0x65, 0x72, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x74, 0x61, 0x67, 0x73, 0x52, 0x09, 0x61, 0x6c, 0x74,
	0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x32, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x75, 0x6d, 0x75,
	0x6c, 0x61, 0x74, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x61, 0x63, 0x63, 0x75, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x0a,
	0x61, 0x63, 0x63, 0x75, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x22, 0xb3, 0x02, 0x0a, 0x0f, 0x6d,
	0x61, 0x74, 0x63, 0x68, 0x5f, 0x73, 0x70, 0x69, 0x6e, 0x5f, 0x73, 0x74, 0x65, 0x70, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x03, 0x70, 0x69, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x75, 0x6d, 0x5f, 0x67, 0x61, 0x69, 0x6e,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x73, 0x75, 0x6d, 0x47, 0x61, 0x69, 0x6e, 0x12,
	0x29, 0x0a, 0x09, 0x69, 0x6e, 0x69, 0x74, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x05, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x74, 0x61, 0x67, 0x73,
	0x52, 0x08, 0x69, 0x6e, 0x69, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x05, 0x66, 0x6c,
	0x6f, 0x77, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x73, 0x74, 0x65, 0x70, 0x5f, 0x66, 0x6c, 0x6f, 0x77, 0x52, 0x05, 0x66, 0x6c,
	0x6f, 0x77, 0x73, 0x12, 0x33, 0x0a, 0x0b, 0x73, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x5f, 0x74, 0x61,
	0x67, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x73, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x5f, 0x74, 0x61, 0x67, 0x52, 0x0a, 0x73, 0x69,
	0x6e, 0x67, 0x6c, 0x65, 0x54, 0x61, 0x67, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x65, 0x6d, 0x5f,
	0x69, 0x6e, 0x69, 0x74, 0x18, 0x08, 0x20, 0x03, 0x28, 0x05, 0x52, 0x07, 0x74, 0x65, 0x6d, 0x49,
	0x6e, 0x69, 0x74, 0x12, 0x2b, 0x0a, 0x0a, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x5f, 0x6c, 0x69, 0x6e,
	0x65, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x74, 0x61, 0x67, 0x73, 0x52, 0x09, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x4c, 0x69, 0x6e, 0x65,
	0x22, 0xc3, 0x02, 0x0a, 0x0e, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x73, 0x70, 0x69, 0x6e, 0x5f,
	0x61, 0x63, 0x6b, 0x12, 0x24, 0x0a, 0x04, 0x68, 0x65, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x61, 0x63, 0x6b, 0x5f, 0x68,
	0x65, 0x61, 0x64, 0x52, 0x04, 0x68, 0x65, 0x61, 0x64, 0x12, 0x22, 0x0a, 0x03, 0x6f, 0x70, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x73, 0x70, 0x69, 0x6e, 0x5f, 0x6f, 0x70, 0x74, 0x52, 0x03, 0x6f, 0x70, 0x74, 0x12, 0x1b, 0x0a,
	0x09, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x77, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x08, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x57, 0x69, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x5f, 0x62, 0x65, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x42, 0x65, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x5f, 0x72, 0x61, 0x69, 0x73, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x52, 0x61, 0x69, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x05, 0x73, 0x74, 0x65, 0x70,
	0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x73, 0x70, 0x69, 0x6e, 0x5f, 0x73, 0x74, 0x65, 0x70,
	0x52, 0x05, 0x73, 0x74, 0x65, 0x70, 0x73, 0x12, 0x15, 0x0a, 0x06, 0x74, 0x78, 0x6e, 0x5f, 0x69,
	0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x74, 0x78, 0x6e, 0x49, 0x64, 0x12, 0x23,
	0x0a, 0x0d, 0x62, 0x65, 0x66, 0x6f, 0x72, 0x65, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x62, 0x65, 0x66, 0x6f, 0x72, 0x65, 0x41, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x66, 0x74, 0x65, 0x72, 0x5f, 0x61, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x61, 0x66, 0x74, 0x65, 0x72,
	0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x21, 0x0a, 0x03, 0x70, 0x6f, 0x73, 0x12, 0x0c, 0x0a,
	0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x79, 0x22, 0x8f, 0x01, 0x0a, 0x0a, 0x73, 0x69,
	0x6e, 0x67, 0x6c, 0x65, 0x5f, 0x74, 0x61, 0x67, 0x12, 0x23, 0x0a, 0x06, 0x73, 0x69, 0x6e, 0x67,
	0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x74, 0x61, 0x67, 0x52, 0x06, 0x73, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x12, 0x1d, 0x0a,
	0x0a, 0x66, 0x6c, 0x6f, 0x77, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x09, 0x66, 0x6c, 0x6f, 0x77, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x26, 0x0a, 0x08,
	0x70, 0x6f, 0x73, 0x5f, 0x6f, 0x64, 0x65, 0x72, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b,
	0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x6f, 0x73, 0x52, 0x07, 0x70, 0x6f, 0x73,
	0x4f, 0x64, 0x65, 0x72, 0x12, 0x15, 0x0a, 0x06, 0x73, 0x75, 0x62, 0x5f, 0x69, 0x64, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x75, 0x62, 0x49, 0x64, 0x22, 0x68, 0x0a, 0x0a, 0x61,
	0x63, 0x63, 0x75, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x67, 0x65, 0x6e,
	0x65, 0x72, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x67, 0x65, 0x6e, 0x65,
	0x72, 0x61, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x65, 0x66, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x6c, 0x65, 0x66, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x69, 0x67, 0x68, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x72, 0x69, 0x67, 0x68, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x70,
	0x6f, 0x69, 0x6e, 0x74, 0x73, 0x42, 0x17, 0x5a, 0x15, 0x65, 0x6c, 0x69, 0x6d, 0x43, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x2f, 0x70, 0x62, 0x73, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_common_matchgame_proto_rawDescOnce sync.Once
	file_proto_common_matchgame_proto_rawDescData = file_proto_common_matchgame_proto_rawDesc
)

func file_proto_common_matchgame_proto_rawDescGZIP() []byte {
	file_proto_common_matchgame_proto_rawDescOnce.Do(func() {
		file_proto_common_matchgame_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_common_matchgame_proto_rawDescData)
	})
	return file_proto_common_matchgame_proto_rawDescData
}

var file_proto_common_matchgame_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_common_matchgame_proto_goTypes = []interface{}{
	(*Tag)(nil),           // 0: common.tag
	(*Tags)(nil),          // 1: common.tags
	(*StepFlow)(nil),      // 2: common.step_flow
	(*MatchSpinStep)(nil), // 3: common.match_spin_step
	(*MatchSpinAck)(nil),  // 4: common.match_spin_ack
	(*Pos)(nil),           // 5: common.pos
	(*SingleTag)(nil),     // 6: common.single_tag
	(*Accumulate)(nil),    // 7: common.accumulate
	(*AckHead)(nil),       // 8: common.ack_head
	(*SpinOpt)(nil),       // 9: common.spin_opt
}
var file_proto_common_matchgame_proto_depIdxs = []int32{
	0,  // 0: common.tags.tags:type_name -> common.tag
	1,  // 1: common.step_flow.remove_list:type_name -> common.tags
	1,  // 2: common.step_flow.add_list:type_name -> common.tags
	5,  // 3: common.step_flow.skill_center:type_name -> common.pos
	1,  // 4: common.step_flow.alter_list:type_name -> common.tags
	7,  // 5: common.step_flow.accumulate:type_name -> common.accumulate
	1,  // 6: common.match_spin_step.init_list:type_name -> common.tags
	2,  // 7: common.match_spin_step.flows:type_name -> common.step_flow
	6,  // 8: common.match_spin_step.single_tags:type_name -> common.single_tag
	1,  // 9: common.match_spin_step.other_line:type_name -> common.tags
	8,  // 10: common.match_spin_ack.head:type_name -> common.ack_head
	9,  // 11: common.match_spin_ack.opt:type_name -> common.spin_opt
	3,  // 12: common.match_spin_ack.steps:type_name -> common.match_spin_step
	0,  // 13: common.single_tag.single:type_name -> common.tag
	5,  // 14: common.single_tag.pos_oder:type_name -> common.pos
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_proto_common_matchgame_proto_init() }
func file_proto_common_matchgame_proto_init() {
	if File_proto_common_matchgame_proto != nil {
		return
	}
	file_proto_common_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_proto_common_matchgame_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tag); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_common_matchgame_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tags); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_common_matchgame_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StepFlow); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_common_matchgame_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MatchSpinStep); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_common_matchgame_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MatchSpinAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_common_matchgame_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pos); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_common_matchgame_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SingleTag); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_common_matchgame_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Accumulate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_common_matchgame_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_common_matchgame_proto_goTypes,
		DependencyIndexes: file_proto_common_matchgame_proto_depIdxs,
		MessageInfos:      file_proto_common_matchgame_proto_msgTypes,
	}.Build()
	File_proto_common_matchgame_proto = out.File
	file_proto_common_matchgame_proto_rawDesc = nil
	file_proto_common_matchgame_proto_goTypes = nil
	file_proto_common_matchgame_proto_depIdxs = nil
}
