// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.26.1
// source: proto/common/backend.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BackendOperate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Head *ReqHead `protobuf:"bytes,1,opt,name=head,proto3" json:"head,omitempty"`  //公共头部
	Type int32    `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"` //操作类型
	Data string   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`  //操作数据
}

func (x *BackendOperate) Reset() {
	*x = BackendOperate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_common_backend_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BackendOperate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackendOperate) ProtoMessage() {}

func (x *BackendOperate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_backend_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackendOperate.ProtoReflect.Descriptor instead.
func (*BackendOperate) Descriptor() ([]byte, []int) {
	return file_proto_common_backend_proto_rawDescGZIP(), []int{0}
}

func (x *BackendOperate) GetHead() *ReqHead {
	if x != nil {
		return x.Head
	}
	return nil
}

func (x *BackendOperate) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *BackendOperate) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type BackendOperateAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Head *AckHead `protobuf:"bytes,1,opt,name=head,proto3" json:"head,omitempty"`  //公共头部
	Type int32    `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"` //操作类型
	Data string   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`  //操作数据
}

func (x *BackendOperateAck) Reset() {
	*x = BackendOperateAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_common_backend_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BackendOperateAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackendOperateAck) ProtoMessage() {}

func (x *BackendOperateAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_backend_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackendOperateAck.ProtoReflect.Descriptor instead.
func (*BackendOperateAck) Descriptor() ([]byte, []int) {
	return file_proto_common_backend_proto_rawDescGZIP(), []int{1}
}

func (x *BackendOperateAck) GetHead() *AckHead {
	if x != nil {
		return x.Head
	}
	return nil
}

func (x *BackendOperateAck) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *BackendOperateAck) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type ClusterOperate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Publisher string `protobuf:"bytes,1,opt,name=publisher,proto3" json:"publisher,omitempty"` //发布者
	Type      int32  `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`          //操作类型
	Data      string `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`           //操作数据
}

func (x *ClusterOperate) Reset() {
	*x = ClusterOperate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_common_backend_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClusterOperate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterOperate) ProtoMessage() {}

func (x *ClusterOperate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_backend_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterOperate.ProtoReflect.Descriptor instead.
func (*ClusterOperate) Descriptor() ([]byte, []int) {
	return file_proto_common_backend_proto_rawDescGZIP(), []int{2}
}

func (x *ClusterOperate) GetPublisher() string {
	if x != nil {
		return x.Publisher
	}
	return ""
}

func (x *ClusterOperate) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *ClusterOperate) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type Ids struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids []uint64 `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"` //id列表
}

func (x *Ids) Reset() {
	*x = Ids{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_common_backend_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ids) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ids) ProtoMessage() {}

func (x *Ids) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_backend_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ids.ProtoReflect.Descriptor instead.
func (*Ids) Descriptor() ([]byte, []int) {
	return file_proto_common_backend_proto_rawDescGZIP(), []int{3}
}

func (x *Ids) GetIds() []uint64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type SurvivalMap struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DaySurvival map[uint32]*SurvivalData `protobuf:"bytes,1,rep,name=day_survival,json=daySurvival,proto3" json:"day_survival,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` //下注
}

func (x *SurvivalMap) Reset() {
	*x = SurvivalMap{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_common_backend_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SurvivalMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SurvivalMap) ProtoMessage() {}

func (x *SurvivalMap) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_backend_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SurvivalMap.ProtoReflect.Descriptor instead.
func (*SurvivalMap) Descriptor() ([]byte, []int) {
	return file_proto_common_backend_proto_rawDescGZIP(), []int{4}
}

func (x *SurvivalMap) GetDaySurvival() map[uint32]*SurvivalData {
	if x != nil {
		return x.DaySurvival
	}
	return nil
}

type SurvivalData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Player int64 `protobuf:"varint,1,opt,name=player,proto3" json:"player,omitempty"` //玩家
	Bk     int64 `protobuf:"varint,2,opt,name=bk,proto3" json:"bk,omitempty"`         //下注
	Rt     int64 `protobuf:"varint,3,opt,name=rt,proto3" json:"rt,omitempty"`         //返回
	Rta    int64 `protobuf:"varint,4,opt,name=rta,proto3" json:"rta,omitempty"`       //返回率
}

func (x *SurvivalData) Reset() {
	*x = SurvivalData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_common_backend_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SurvivalData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SurvivalData) ProtoMessage() {}

func (x *SurvivalData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_backend_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SurvivalData.ProtoReflect.Descriptor instead.
func (*SurvivalData) Descriptor() ([]byte, []int) {
	return file_proto_common_backend_proto_rawDescGZIP(), []int{5}
}

func (x *SurvivalData) GetPlayer() int64 {
	if x != nil {
		return x.Player
	}
	return 0
}

func (x *SurvivalData) GetBk() int64 {
	if x != nil {
		return x.Bk
	}
	return 0
}

func (x *SurvivalData) GetRt() int64 {
	if x != nil {
		return x.Rt
	}
	return 0
}

func (x *SurvivalData) GetRta() int64 {
	if x != nil {
		return x.Rta
	}
	return 0
}

type BkPlayer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerBkMap map[uint64]int64 `protobuf:"bytes,1,rep,name=player_bk_map,json=playerBkMap,proto3" json:"player_bk_map,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"` //下注
}

func (x *BkPlayer) Reset() {
	*x = BkPlayer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_common_backend_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BkPlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BkPlayer) ProtoMessage() {}

func (x *BkPlayer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_backend_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BkPlayer.ProtoReflect.Descriptor instead.
func (*BkPlayer) Descriptor() ([]byte, []int) {
	return file_proto_common_backend_proto_rawDescGZIP(), []int{6}
}

func (x *BkPlayer) GetPlayerBkMap() map[uint64]int64 {
	if x != nil {
		return x.PlayerBkMap
	}
	return nil
}

var File_proto_common_backend_proto protoreflect.FileDescriptor

var file_proto_common_backend_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x62,
	0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x1a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x5f, 0x0a, 0x0f, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x5f, 0x6f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x65, 0x12, 0x24, 0x0a, 0x04, 0x68, 0x65, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x72, 0x65, 0x71, 0x5f, 0x68, 0x65,
	0x61, 0x64, 0x52, 0x04, 0x68, 0x65, 0x61, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x22, 0x63, 0x0a, 0x13, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x5f, 0x6f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x65, 0x5f, 0x61, 0x63, 0x6b, 0x12, 0x24, 0x0a, 0x04, 0x68, 0x65, 0x61, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x61,
	0x63, 0x6b, 0x5f, 0x68, 0x65, 0x61, 0x64, 0x52, 0x04, 0x68, 0x65, 0x61, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x57, 0x0a, 0x0f, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72,
	0x5f, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x75, 0x62, 0x6c,
	0x69, 0x73, 0x68, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x75, 0x62,
	0x6c, 0x69, 0x73, 0x68, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x17,
	0x0a, 0x03, 0x69, 0x64, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x04, 0x52, 0x03, 0x69, 0x64, 0x73, 0x22, 0xaf, 0x01, 0x0a, 0x0c, 0x73, 0x75, 0x72, 0x76,
	0x69, 0x76, 0x61, 0x6c, 0x5f, 0x6d, 0x61, 0x70, 0x12, 0x48, 0x0a, 0x0c, 0x64, 0x61, 0x79, 0x5f,
	0x73, 0x75, 0x72, 0x76, 0x69, 0x76, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x25,
	0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x73, 0x75, 0x72, 0x76, 0x69, 0x76, 0x61, 0x6c,
	0x5f, 0x6d, 0x61, 0x70, 0x2e, 0x44, 0x61, 0x79, 0x53, 0x75, 0x72, 0x76, 0x69, 0x76, 0x61, 0x6c,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0b, 0x64, 0x61, 0x79, 0x53, 0x75, 0x72, 0x76, 0x69, 0x76,
	0x61, 0x6c, 0x1a, 0x55, 0x0a, 0x10, 0x44, 0x61, 0x79, 0x53, 0x75, 0x72, 0x76, 0x69, 0x76, 0x61,
	0x6c, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2b, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x73, 0x75, 0x72, 0x76, 0x69, 0x76, 0x61, 0x6c, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x59, 0x0a, 0x0d, 0x73, 0x75, 0x72,
	0x76, 0x69, 0x76, 0x61, 0x6c, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x62, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x62, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x72, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x03, 0x72, 0x74, 0x61, 0x22, 0x93, 0x01, 0x0a, 0x09, 0x62, 0x6b, 0x5f, 0x70, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x12, 0x46, 0x0a, 0x0d, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x62, 0x6b, 0x5f,
	0x6d, 0x61, 0x70, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x62, 0x6b, 0x5f, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x2e, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x42, 0x6b, 0x4d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0b, 0x70,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x42, 0x6b, 0x4d, 0x61, 0x70, 0x1a, 0x3e, 0x0a, 0x10, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x42, 0x6b, 0x4d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x42, 0x12, 0x5a, 0x10, 0x65, 0x6c,
	0x69, 0x6d, 0x35, 0x2f, 0x70, 0x62, 0x73, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_common_backend_proto_rawDescOnce sync.Once
	file_proto_common_backend_proto_rawDescData = file_proto_common_backend_proto_rawDesc
)

func file_proto_common_backend_proto_rawDescGZIP() []byte {
	file_proto_common_backend_proto_rawDescOnce.Do(func() {
		file_proto_common_backend_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_common_backend_proto_rawDescData)
	})
	return file_proto_common_backend_proto_rawDescData
}

var file_proto_common_backend_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_common_backend_proto_goTypes = []interface{}{
	(*BackendOperate)(nil),    // 0: common.backend_operate
	(*BackendOperateAck)(nil), // 1: common.backend_operate_ack
	(*ClusterOperate)(nil),    // 2: common.cluster_operate
	(*Ids)(nil),               // 3: common.ids
	(*SurvivalMap)(nil),       // 4: common.survival_map
	(*SurvivalData)(nil),      // 5: common.survival_data
	(*BkPlayer)(nil),          // 6: common.bk_player
	nil,                       // 7: common.survival_map.DaySurvivalEntry
	nil,                       // 8: common.bk_player.PlayerBkMapEntry
	(*ReqHead)(nil),           // 9: common.req_head
	(*AckHead)(nil),           // 10: common.ack_head
}
var file_proto_common_backend_proto_depIdxs = []int32{
	9,  // 0: common.backend_operate.head:type_name -> common.req_head
	10, // 1: common.backend_operate_ack.head:type_name -> common.ack_head
	7,  // 2: common.survival_map.day_survival:type_name -> common.survival_map.DaySurvivalEntry
	8,  // 3: common.bk_player.player_bk_map:type_name -> common.bk_player.PlayerBkMapEntry
	5,  // 4: common.survival_map.DaySurvivalEntry.value:type_name -> common.survival_data
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_common_backend_proto_init() }
func file_proto_common_backend_proto_init() {
	if File_proto_common_backend_proto != nil {
		return
	}
	file_proto_common_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_proto_common_backend_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BackendOperate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_common_backend_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BackendOperateAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_common_backend_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClusterOperate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_common_backend_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ids); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_common_backend_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SurvivalMap); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_common_backend_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SurvivalData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_common_backend_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BkPlayer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_common_backend_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_common_backend_proto_goTypes,
		DependencyIndexes: file_proto_common_backend_proto_depIdxs,
		MessageInfos:      file_proto_common_backend_proto_msgTypes,
	}.Build()
	File_proto_common_backend_proto = out.File
	file_proto_common_backend_proto_rawDesc = nil
	file_proto_common_backend_proto_goTypes = nil
	file_proto_common_backend_proto_depIdxs = nil
}
