// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.26.1
// source: proto/common/login.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 用户登录请求
type LoginReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Head      *ReqHead `protobuf:"bytes,1,opt,name=head,proto3" json:"head,omitempty"`
	Username  string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`                     //账号
	Password  string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`                     //密码
	Phone     string   `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`                           //手机号
	Pkg       string   `protobuf:"bytes,5,opt,name=pkg,proto3" json:"pkg,omitempty"`                               //渠道包
	ProjectId int32    `protobuf:"varint,6,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"` //项目id
	Currency  string   `protobuf:"bytes,7,opt,name=currency,proto3" json:"currency,omitempty"`                     //货币
	GameId    int32    `protobuf:"varint,8,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`          //游戏id
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_common_login_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_login_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_proto_common_login_proto_rawDescGZIP(), []int{0}
}

func (x *LoginReq) GetHead() *ReqHead {
	if x != nil {
		return x.Head
	}
	return nil
}

func (x *LoginReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *LoginReq) GetPkg() string {
	if x != nil {
		return x.Pkg
	}
	return ""
}

func (x *LoginReq) GetProjectId() int32 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *LoginReq) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *LoginReq) GetGameId() int32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

// 用户登录回复
type LoginAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Head         *AckHead    `protobuf:"bytes,1,opt,name=head,proto3" json:"head,omitempty"`                                      //公共头部
	Uid          int32       `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`                                       //用户唯一id
	Username     string      `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`                              //账号
	Token        string      `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`                                    //token信息
	Amount       int64       `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`                                 //余额
	GameList     []*GameInfo `protobuf:"bytes,6,rep,name=game_list,json=gameList,proto3" json:"game_list,omitempty"`              //大厅列表
	Currency     string      `protobuf:"bytes,7,opt,name=currency,proto3" json:"currency,omitempty"`                              //货币
	AmountLimits int64       `protobuf:"varint,8,opt,name=amount_limits,json=amountLimits,proto3" json:"amount_limits,omitempty"` //余额限制
}

func (x *LoginAck) Reset() {
	*x = LoginAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_common_login_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginAck) ProtoMessage() {}

func (x *LoginAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_login_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginAck.ProtoReflect.Descriptor instead.
func (*LoginAck) Descriptor() ([]byte, []int) {
	return file_proto_common_login_proto_rawDescGZIP(), []int{1}
}

func (x *LoginAck) GetHead() *AckHead {
	if x != nil {
		return x.Head
	}
	return nil
}

func (x *LoginAck) GetUid() int32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *LoginAck) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginAck) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginAck) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *LoginAck) GetGameList() []*GameInfo {
	if x != nil {
		return x.GameList
	}
	return nil
}

func (x *LoginAck) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *LoginAck) GetAmountLimits() int64 {
	if x != nil {
		return x.AmountLimits
	}
	return 0
}

// 游戏信息
type GameInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                            //游戏id
	Name     string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                         //游戏名称
	Icon     string  `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon,omitempty"`                         //游戏图标
	Url      string  `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`                           //游戏地址
	Status   int32   `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`                    //游戏状态 1开启 2关闭 3未完成
	Config   string  `protobuf:"bytes,6,opt,name=config,proto3" json:"config,omitempty"`                     //游戏配置
	FileList []*File `protobuf:"bytes,7,rep,name=file_list,json=fileList,proto3" json:"file_list,omitempty"` //文件列表
}

func (x *GameInfo) Reset() {
	*x = GameInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_common_login_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameInfo) ProtoMessage() {}

func (x *GameInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_login_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameInfo.ProtoReflect.Descriptor instead.
func (*GameInfo) Descriptor() ([]byte, []int) {
	return file_proto_common_login_proto_rawDescGZIP(), []int{2}
}

func (x *GameInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GameInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GameInfo) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *GameInfo) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *GameInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GameInfo) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

func (x *GameInfo) GetFileList() []*File {
	if x != nil {
		return x.FileList
	}
	return nil
}

type IntoGame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Head     *ReqHead `protobuf:"bytes,1,opt,name=head,proto3" json:"head,omitempty"`
	GameId   int32    `protobuf:"varint,2,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`       //游戏id
	PlayType int32    `protobuf:"varint,3,opt,name=play_type,json=playType,proto3" json:"play_type,omitempty"` //玩法类型
}

func (x *IntoGame) Reset() {
	*x = IntoGame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_common_login_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IntoGame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntoGame) ProtoMessage() {}

func (x *IntoGame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_login_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntoGame.ProtoReflect.Descriptor instead.
func (*IntoGame) Descriptor() ([]byte, []int) {
	return file_proto_common_login_proto_rawDescGZIP(), []int{3}
}

func (x *IntoGame) GetHead() *ReqHead {
	if x != nil {
		return x.Head
	}
	return nil
}

func (x *IntoGame) GetGameId() int32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *IntoGame) GetPlayType() int32 {
	if x != nil {
		return x.PlayType
	}
	return 0
}

// 进入游戏回复
type IntoGameAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Head    *AckHead     `protobuf:"bytes,1,opt,name=head,proto3" json:"head,omitempty"`
	Bet     []int64      `protobuf:"varint,2,rep,packed,name=bet,proto3" json:"bet,omitempty"` //下注
	Data    *GameRecover `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`       //游戏恢复数据
	SpinAck []byte       `protobuf:"bytes,4,opt,name=spinAck,proto3" json:"spinAck,omitempty"` // spinAck数据
}

func (x *IntoGameAck) Reset() {
	*x = IntoGameAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_common_login_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IntoGameAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntoGameAck) ProtoMessage() {}

func (x *IntoGameAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_login_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntoGameAck.ProtoReflect.Descriptor instead.
func (*IntoGameAck) Descriptor() ([]byte, []int) {
	return file_proto_common_login_proto_rawDescGZIP(), []int{4}
}

func (x *IntoGameAck) GetHead() *AckHead {
	if x != nil {
		return x.Head
	}
	return nil
}

func (x *IntoGameAck) GetBet() []int64 {
	if x != nil {
		return x.Bet
	}
	return nil
}

func (x *IntoGameAck) GetData() *GameRecover {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *IntoGameAck) GetSpinAck() []byte {
	if x != nil {
		return x.SpinAck
	}
	return nil
}

// 用户登出请求(暂未使用)
type LogoutReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Head *ReqHead `protobuf:"bytes,1,opt,name=head,proto3" json:"head,omitempty"`
}

func (x *LogoutReq) Reset() {
	*x = LogoutReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_common_login_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogoutReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutReq) ProtoMessage() {}

func (x *LogoutReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_login_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutReq.ProtoReflect.Descriptor instead.
func (*LogoutReq) Descriptor() ([]byte, []int) {
	return file_proto_common_login_proto_rawDescGZIP(), []int{5}
}

func (x *LogoutReq) GetHead() *ReqHead {
	if x != nil {
		return x.Head
	}
	return nil
}

// 用户登出回复(暂未使用)
type LogoutAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Head *AckHead `protobuf:"bytes,1,opt,name=head,proto3" json:"head,omitempty"` //公共头部
}

func (x *LogoutAck) Reset() {
	*x = LogoutAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_common_login_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogoutAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutAck) ProtoMessage() {}

func (x *LogoutAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_login_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutAck.ProtoReflect.Descriptor instead.
func (*LogoutAck) Descriptor() ([]byte, []int) {
	return file_proto_common_login_proto_rawDescGZIP(), []int{6}
}

func (x *LogoutAck) GetHead() *AckHead {
	if x != nil {
		return x.Head
	}
	return nil
}

// 商户用户登录请求
type MerchantLoginReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Head   *ReqHead `protobuf:"bytes,1,opt,name=head,proto3" json:"head,omitempty"`
	GameId int32    `protobuf:"varint,2,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"` //游戏id
}

func (x *MerchantLoginReq) Reset() {
	*x = MerchantLoginReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_common_login_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MerchantLoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerchantLoginReq) ProtoMessage() {}

func (x *MerchantLoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_login_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerchantLoginReq.ProtoReflect.Descriptor instead.
func (*MerchantLoginReq) Descriptor() ([]byte, []int) {
	return file_proto_common_login_proto_rawDescGZIP(), []int{7}
}

func (x *MerchantLoginReq) GetHead() *ReqHead {
	if x != nil {
		return x.Head
	}
	return nil
}

func (x *MerchantLoginReq) GetGameId() int32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

// 商户用户登录回复
type MerchantLoginAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Head         *AckHead    `protobuf:"bytes,1,opt,name=head,proto3" json:"head,omitempty"`                                      //公共头部
	Uid          int32       `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`                                       //用户唯一id
	Username     string      `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`                              //账号
	Token        string      `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`                                    //token信息
	Amount       int64       `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`                                 //余额
	GameList     []*GameInfo `protobuf:"bytes,6,rep,name=game_list,json=gameList,proto3" json:"game_list,omitempty"`              //大厅列表
	Currency     string      `protobuf:"bytes,7,opt,name=currency,proto3" json:"currency,omitempty"`                              //货币
	AmountLimits int64       `protobuf:"varint,8,opt,name=amount_limits,json=amountLimits,proto3" json:"amount_limits,omitempty"` //余额限制
	FileList     []*File     `protobuf:"bytes,9,rep,name=file_list,json=fileList,proto3" json:"file_list,omitempty"`              //文件列表
}

func (x *MerchantLoginAck) Reset() {
	*x = MerchantLoginAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_common_login_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MerchantLoginAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerchantLoginAck) ProtoMessage() {}

func (x *MerchantLoginAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_login_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerchantLoginAck.ProtoReflect.Descriptor instead.
func (*MerchantLoginAck) Descriptor() ([]byte, []int) {
	return file_proto_common_login_proto_rawDescGZIP(), []int{8}
}

func (x *MerchantLoginAck) GetHead() *AckHead {
	if x != nil {
		return x.Head
	}
	return nil
}

func (x *MerchantLoginAck) GetUid() int32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *MerchantLoginAck) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *MerchantLoginAck) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *MerchantLoginAck) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *MerchantLoginAck) GetGameList() []*GameInfo {
	if x != nil {
		return x.GameList
	}
	return nil
}

func (x *MerchantLoginAck) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *MerchantLoginAck) GetAmountLimits() int64 {
	if x != nil {
		return x.AmountLimits
	}
	return 0
}

func (x *MerchantLoginAck) GetFileList() []*File {
	if x != nil {
		return x.FileList
	}
	return nil
}

type File struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` //文件名
	Path string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"` //文件路径
}

func (x *File) Reset() {
	*x = File{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_common_login_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_login_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_proto_common_login_proto_rawDescGZIP(), []int{9}
}

func (x *File) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *File) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

var File_proto_common_login_proto protoreflect.FileDescriptor

var file_proto_common_login_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x6c,
	0x6f, 0x67, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x1a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe5, 0x01,
	0x0a, 0x09, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x72, 0x65, 0x71, 0x12, 0x24, 0x0a, 0x04, 0x68,
	0x65, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x72, 0x65, 0x71, 0x5f, 0x68, 0x65, 0x61, 0x64, 0x52, 0x04, 0x68, 0x65, 0x61,
	0x64, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f,
	0x6e, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x70, 0x6b, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x70, 0x6b,
	0x67, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64,
	0x12, 0x1a, 0x0a, 0x08, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x17, 0x0a, 0x07,
	0x67, 0x61, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x67,
	0x61, 0x6d, 0x65, 0x49, 0x64, 0x22, 0xfe, 0x01, 0x0a, 0x09, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f,
	0x61, 0x63, 0x6b, 0x12, 0x24, 0x0a, 0x04, 0x68, 0x65, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x61, 0x63, 0x6b, 0x5f, 0x68,
	0x65, 0x61, 0x64, 0x52, 0x04, 0x68, 0x65, 0x61, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x75,
	0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75,
	0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x16, 0x0a,
	0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x61,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x2e, 0x0a, 0x09, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x6c, 0x69,
	0x73, 0x74, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x67, 0x61, 0x6d,
	0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63,
	0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63,
	0x79, 0x12, 0x23, 0x0a, 0x0d, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x6c, 0x69, 0x6d, 0x69,
	0x74, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x4c, 0x69, 0x6d, 0x69, 0x74, 0x73, 0x22, 0xb0, 0x01, 0x0a, 0x09, 0x67, 0x61, 0x6d, 0x65, 0x5f,
	0x69, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x63, 0x6f, 0x6e,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x63, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03,
	0x75, 0x72, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x29,
	0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x07, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x52,
	0x08, 0x66, 0x69, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x67, 0x0a, 0x09, 0x69, 0x6e, 0x74,
	0x6f, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x12, 0x24, 0x0a, 0x04, 0x68, 0x65, 0x61, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x72, 0x65,
	0x71, 0x5f, 0x68, 0x65, 0x61, 0x64, 0x52, 0x04, 0x68, 0x65, 0x61, 0x64, 0x12, 0x17, 0x0a, 0x07,
	0x67, 0x61, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x67,
	0x61, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x54, 0x79,
	0x70, 0x65, 0x22, 0x8b, 0x01, 0x0a, 0x0d, 0x69, 0x6e, 0x74, 0x6f, 0x5f, 0x67, 0x61, 0x6d, 0x65,
	0x5f, 0x61, 0x63, 0x6b, 0x12, 0x24, 0x0a, 0x04, 0x68, 0x65, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x61, 0x63, 0x6b, 0x5f,
	0x68, 0x65, 0x61, 0x64, 0x52, 0x04, 0x68, 0x65, 0x61, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x62, 0x65,
	0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x03, 0x52, 0x03, 0x62, 0x65, 0x74, 0x12, 0x28, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x72, 0x65, 0x63, 0x6f, 0x76, 0x65, 0x72,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x70, 0x69, 0x6e, 0x41, 0x63,
	0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x73, 0x70, 0x69, 0x6e, 0x41, 0x63, 0x6b,
	0x22, 0x32, 0x0a, 0x0a, 0x6c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x5f, 0x72, 0x65, 0x71, 0x12, 0x24,
	0x0a, 0x04, 0x68, 0x65, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x72, 0x65, 0x71, 0x5f, 0x68, 0x65, 0x61, 0x64, 0x52, 0x04,
	0x68, 0x65, 0x61, 0x64, 0x22, 0x32, 0x0a, 0x0a, 0x6c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x5f, 0x61,
	0x63, 0x6b, 0x12, 0x24, 0x0a, 0x04, 0x68, 0x65, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x61, 0x63, 0x6b, 0x5f, 0x68, 0x65,
	0x61, 0x64, 0x52, 0x04, 0x68, 0x65, 0x61, 0x64, 0x22, 0x53, 0x0a, 0x12, 0x6d, 0x65, 0x72, 0x63,
	0x68, 0x61, 0x6e, 0x74, 0x5f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x72, 0x65, 0x71, 0x12, 0x24,
	0x0a, 0x04, 0x68, 0x65, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x72, 0x65, 0x71, 0x5f, 0x68, 0x65, 0x61, 0x64, 0x52, 0x04,
	0x68, 0x65, 0x61, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x22, 0xb2, 0x02,
	0x0a, 0x12, 0x6d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x5f, 0x6c, 0x6f, 0x67, 0x69, 0x6e,
	0x5f, 0x61, 0x63, 0x6b, 0x12, 0x24, 0x0a, 0x04, 0x68, 0x65, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x61, 0x63, 0x6b, 0x5f,
	0x68, 0x65, 0x61, 0x64, 0x52, 0x04, 0x68, 0x65, 0x61, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08,
	0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x16,
	0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x2e, 0x0a, 0x09, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x6c,
	0x69, 0x73, 0x74, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x67, 0x61,
	0x6d, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e,
	0x63, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e,
	0x63, 0x79, 0x12, 0x23, 0x0a, 0x0d, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x6c, 0x69, 0x6d,
	0x69, 0x74, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x61, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x73, 0x12, 0x29, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f,
	0x6c, 0x69, 0x73, 0x74, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4c, 0x69,
	0x73, 0x74, 0x22, 0x2e, 0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61,
	0x74, 0x68, 0x42, 0x12, 0x5a, 0x10, 0x65, 0x6c, 0x69, 0x6d, 0x35, 0x2f, 0x70, 0x62, 0x73, 0x2f,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_common_login_proto_rawDescOnce sync.Once
	file_proto_common_login_proto_rawDescData = file_proto_common_login_proto_rawDesc
)

func file_proto_common_login_proto_rawDescGZIP() []byte {
	file_proto_common_login_proto_rawDescOnce.Do(func() {
		file_proto_common_login_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_common_login_proto_rawDescData)
	})
	return file_proto_common_login_proto_rawDescData
}

var file_proto_common_login_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_common_login_proto_goTypes = []interface{}{
	(*LoginReq)(nil),         // 0: common.login_req
	(*LoginAck)(nil),         // 1: common.login_ack
	(*GameInfo)(nil),         // 2: common.game_info
	(*IntoGame)(nil),         // 3: common.into_game
	(*IntoGameAck)(nil),      // 4: common.into_game_ack
	(*LogoutReq)(nil),        // 5: common.logout_req
	(*LogoutAck)(nil),        // 6: common.logout_ack
	(*MerchantLoginReq)(nil), // 7: common.merchant_login_req
	(*MerchantLoginAck)(nil), // 8: common.merchant_login_ack
	(*File)(nil),             // 9: common.file
	(*ReqHead)(nil),          // 10: common.req_head
	(*AckHead)(nil),          // 11: common.ack_head
	(*GameRecover)(nil),      // 12: common.game_recover
}
var file_proto_common_login_proto_depIdxs = []int32{
	10, // 0: common.login_req.head:type_name -> common.req_head
	11, // 1: common.login_ack.head:type_name -> common.ack_head
	2,  // 2: common.login_ack.game_list:type_name -> common.game_info
	9,  // 3: common.game_info.file_list:type_name -> common.file
	10, // 4: common.into_game.head:type_name -> common.req_head
	11, // 5: common.into_game_ack.head:type_name -> common.ack_head
	12, // 6: common.into_game_ack.data:type_name -> common.game_recover
	10, // 7: common.logout_req.head:type_name -> common.req_head
	11, // 8: common.logout_ack.head:type_name -> common.ack_head
	10, // 9: common.merchant_login_req.head:type_name -> common.req_head
	11, // 10: common.merchant_login_ack.head:type_name -> common.ack_head
	2,  // 11: common.merchant_login_ack.game_list:type_name -> common.game_info
	9,  // 12: common.merchant_login_ack.file_list:type_name -> common.file
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_proto_common_login_proto_init() }
func file_proto_common_login_proto_init() {
	if File_proto_common_login_proto != nil {
		return
	}
	file_proto_common_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_proto_common_login_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_common_login_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_common_login_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_common_login_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IntoGame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_common_login_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IntoGameAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_common_login_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogoutReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_common_login_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogoutAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_common_login_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MerchantLoginReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_common_login_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MerchantLoginAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_common_login_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*File); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_common_login_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_common_login_proto_goTypes,
		DependencyIndexes: file_proto_common_login_proto_depIdxs,
		MessageInfos:      file_proto_common_login_proto_msgTypes,
	}.Build()
	File_proto_common_login_proto = out.File
	file_proto_common_login_proto_rawDesc = nil
	file_proto_common_login_proto_goTypes = nil
	file_proto_common_login_proto_depIdxs = nil
}
